theme: jekyll-theme-leap-day
lang: "en-US"
title: "Organizer -- DataWhys 2020 Summer Internship"
description: "Everything you need to know to make the most out of your internship"
keywords: "DataWhys, internship, data science, NSF"
maintainer_url: "https://olney.ai"
maintainer_name: "Andrew Olney""
